### ISSUE TITLE
Problem running counterfit Ubuntu

### ISSUE THREAD

**Issue by jcaldeira1977** [CounterFit-IoT/CounterFit#19]
Hi,

Until today I was able to install and run counterfit on my VM Ubuntu 20.04 with python3.8.10.

Today after a successful counterfit installation (pip install CounterFit) when I try to run it I get the following error:

ubuntu@ubunu2004:$ counterfit
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/counterfit", line 5, in <module>
    from CounterFit.counterfit import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/CounterFit/counterfit.py", line 9, in <module>
    from eventlet import event
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/patcher.py", line 132, in import_patched
    return inject(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dns/zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dns/zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'
ubuntu@ubunu2004:$

Can I get some help solving this issue?

Thanks.

**Comment by vipulrai91** [comment]
@jcaldeira1977 - I found a temporary solution, it has to do with the package dnspython.
Run ```pip install dnspython==2.2.1```
This should fix the issue.

Ref - https://stackoverflow.com/questions/75137717/eventlet-dns-python-attribute-error-module-dns-rdtypes-has-no-attribute-any

**Comment by jcaldeira1977** [comment]
@vipulrai91 I managed to solve the problem with the same solution you propose.

Glad you managed it too, I forgot to post it when I found it.
