### ISSUE TITLE
Unable to run CounterFit on VS Code 

### ISSUE THREAD

**Issue by stridefox** [CounterFit-IoT/CounterFit#28]
Hi, I have been trying to learn IoT and I found out about CounterFit. While it worked earlier on, it is not working now. Issue seems to be with a module under **werkzeug**. I have uninstalled and reinstalled the module along with its requirements. I am still unable to figure out the issue. Please help.
```
 (CodeIoT) D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Scripts>counterfit
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Scripts\counterfit.exe\__main__.py", line 4, in <module>
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Lib\site-packages\CounterFit\counterfit.py", line 11, in <module>
    from eventlet import event
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Lib\site-packages\eventlet\support\greendns.py", line 45, in <module>
    from eventlet.green import ssl
  File "D:\Rohan S Gurumurthy\Coding\Python\IoT\CodeIoT\Lib\site-packages\eventlet\green\ssl.py", line 25, in <module>
    _original_wrap_socket = __ssl.wrap_socket
                            ^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

**Comment by Riccardo126** [comment]
Seems new version of werkzeug deprecated a method that can cause some problems.
Just for temporary workaround its possible to do
`pip uninstall werkzeug`
and then
`pip install werkzeug==2.0.0`
Let me know if this solves the issue

**Comment by stridefox** [comment]
Hello Ricardo,
This solution works. Thanks for your input!

Regards,
Rohan

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
