### ISSUE TITLE
unable to run app.py

### ISSUE THREAD

**Issue by zshawk1992** [CounterFit-IoT/CounterFit#31]
**when I run single command counterfit ，it will work，but I run python app.py,it give me many bugs below.
I don't know what happen,I change the port ,but it still not work,can you tell me how to fix it,thanks**

F:\vsworkspace\hamony-ts>python app.py
Traceback (most recent call last):
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 497, in _make_request
    conn.request(
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "E:\tools\anaconda3\Lib\http\client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\tools\anaconda3\Lib\http\client.py", line 1048, in _send_output
    self.send(msg)
  File "E:\tools\anaconda3\Lib\http\client.py", line 986, in send
    self.connect()
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002400396FC90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\tools\anaconda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /connect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002400396FC90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\vsworkspace\hamony-ts\app.py", line 2, in <module>
    CounterFitConnection.init('127.0.0.1', 5000)
  File "E:\tools\anaconda3\Lib\site-packages\counterfit_connection.py", line 42, in init
    requests.post(CounterFitConnection.base_url + 'connect')
  File "E:\tools\anaconda3\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\anaconda3\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /connect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002400396FC90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by zshawk1992** [comment]
I fix it, it's my problem
